FROM alpine
COPY bootstrap.sh /
RUN chmod a+x /bootstrap.sh
RUN bootstrap.sh

#COPY sketch ./
#COPY . .
#EXPOSE 3000


#RUN pacman -Syu
#RUN groupadd -g 1000 kof
#RUN useradd -d /home/kof -s /bin/bash -m kof -u 1000 -g 1000
#USER kof
#ENV HOME /home/kof
##CMD /usr/bin/pp
